core/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    
    path('', views.home, name='home'),
    path('about/', views.aboutUs, name='about'),
    path('contact-us/', views.contactUs, name='contact-us'),
    path('<int:id>/', views.studentDetails, name='studentDetails'),
    path('university/<int:id>/', views.universityDetails, name='universityDetails'),
    
    path('initiate_payment/<int:id>/', views.initiate_payment, name='initiate_payment'),
    path('<str:ref>/', views.verify_payment, name='verify-payment'),
    
    
    path('accounts/', include('authentications.urls')),
    
    path('university/', include('university.urls')),
    path('contributor/', include('contributors.urls')),
    path('student/', include('students.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/models.py
from django.db import models
from django.utils.safestring import mark_safe
from PIL import Image
from authentications.models import User
from university.models import University
from django.utils import timezone
from datetime import date

# Create your models here.
class Student(models.Model):
    GENDER = [
        ("Male", "Male"),
        ("Female", "Female")
    ]
    user = models.OneToOneField(User, related_name='user', on_delete=models.CASCADE)
    student_id = models.CharField(max_length=50)
    university = models.ForeignKey(University, on_delete=models.CASCADE, related_name='student_university_id')
    full_name = models.CharField(max_length=255)
    profile_picture = models.ImageField(default='default.png', upload_to='Student/profile_pictures', blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER)
    phone_number = models.CharField(max_length=12, blank=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)
    
    
    def thumbnail(self):
        return mark_safe("<img src='%s' width='50' height='50' style='object-fit: cover; border-radius: 6px' />" % (self.profile_picture.url))
    
    
    
    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Students'
    
    def __str__(self):
        return self.user.email



class StudentCampaign(models.Model):
    CAMPAIGN_STATUS = (
        ('Ongoing', 'Ongoing'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    
    user = models.ForeignKey(Student, related_name='campaign_student', on_delete=models.CASCADE)
    student_credentials = models.ImageField(upload_to='student/credentials')
    student_university = models.ForeignKey(University, on_delete=models.CASCADE, related_name='campaign_student_university')    
    financial_need = models.DecimalField(max_digits=10, decimal_places=2)
    amount_raised = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    amount_left = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    campaign_message = models.TextField()
    campaign_status = models.CharField(max_length=15, choices=CAMPAIGN_STATUS, default='Ongoing')
    payment_deadline = models.DateField()
    is_approve = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Student Campaign'
        verbose_name_plural = 'Student Campaigns'
        
    # Add helper function for Admin display 
    def full_name(self):
        return f'{self.user.full_name}'
    
    @property
    def days_remaining(self):
        today = date.today()
        remaining = self.payment_deadline.date() - today
        return remaining
    

    def __str__(self):
        return f'{self.user.full_name}'
    

templates/auth_base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Home || Qrowd </title>
    <!-- favicons Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">
    <meta name="description" content="Qrowd HTML 5 Template ">

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">

    <link href="../css2-1?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link rel="stylesheet" href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/animate/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/animate/custom-animate.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/jarallax/jarallax.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/jquery-magnific-popup/jquery.magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/nouislider/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/nouislider/nouislider.pips.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/odometer/odometer.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/swiper/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/qrowd-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/tiny-slider/tiny-slider.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/reey-font/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bxslider/jquery.bxslider.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-select/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/vegas/vegas.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/timepicker/timePicker.css' %}">

    <!-- template styles -->
    <link rel="stylesheet" href="{% static 'css/qrowd.css' %}">
    <link rel="stylesheet" href="{% static 'css/qrowd-responsive.css' %}">
</head>

<body class="custom-cursor">

    <div class="custom-cursor__cursor"></div>
    <div class="custom-cursor__cursor-two"></div>





    {% comment %} <div class="preloader">
        <div class="preloader__image"></div>
    </div> {% endcomment %}
    <!-- /.preloader -->


    <div class="page-wrapper">
        {% include 'includes/navbar.html' %}

        {% block content_wrapper %}
        
        {% endblock  %}

        <!--Site Footer Start-->
        {% include 'includes/footer.html' %}
        <!--Site Footer End-->


    </div><!-- /.page-wrapper -->


    {% include 'includes/mobile-nav.html' %}
    <!-- /.mobile-nav__wrapper -->

    <div class="search-popup">
        <div class="search-popup__overlay search-toggler"></div>
        <!-- /.search-popup__overlay -->
        <div class="search-popup__content">
            <form action="#">
                <label for="search" class="sr-only">search here</label><!-- /.sr-only -->
                <input type="text" id="search" placeholder="Search Here...">
                <button type="submit" aria-label="search submit" class="thm-btn">
                    <i class="icon-magnifying-glass"></i>
                </button>
            </form>
        </div>
        <!-- /.search-popup__content -->
    </div>
    <!-- /.search-popup -->

    <a href="#" data-target="html" class="scroll-to-target scroll-to-top"><i class="icon-right-arrow"></i></a>


    <script src="{% static 'vendors/jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendors/jarallax/jarallax.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-appear/jquery.appear.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-circle-progress/jquery.circle-progress.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-validate/jquery.validate.min.js' %}"></script>
    <script src="{% static 'vendors/nouislider/nouislider.min.js' %}"></script>
    <script src="{% static 'vendors/odometer/odometer.min.js' %}"></script>
    <script src="{% static 'vendors/swiper/swiper.min.js' %}"></script>
    <script src="{% static 'vendors/tiny-slider/tiny-slider.min.js' %}"></script>
    <script src="{% static 'vendors/wnumb/wNumb.min.js' %}"></script>
    <script src="{% static 'vendors/wow/wow.js' %}"></script>
    <script src="{% static 'vendors/isotope/isotope.js' %}"></script>
    <script src="{% static 'vendors/countdown/countdown.min.js' %}"></script>
    <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'vendors/bxslider/jquery.bxslider.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'vendors/vegas/vegas.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'vendors/timepicker/timePicker.js' %}"></script>
    <script src="{% static 'vendors/circleType/jquery.circleType.js' %}"></script>
    <script src="{% static 'vendors/circleType/jquery.lettering.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>




    <!-- template js -->
    <script src="{% static 'js/qrowd.js' %}"></script>
</body>

</html>

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Home || Qrowd </title>
    <!-- favicons Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">
    <meta name="description" content="Qrowd HTML 5 Template ">

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">

    <link href="../css2-1?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link rel="stylesheet" href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/animate/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/animate/custom-animate.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/jarallax/jarallax.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/jquery-magnific-popup/jquery.magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/nouislider/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/nouislider/nouislider.pips.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/odometer/odometer.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/swiper/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/qrowd-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/tiny-slider/tiny-slider.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/reey-font/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bxslider/jquery.bxslider.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-select/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/vegas/vegas.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/timepicker/timePicker.css' %}">

    <!-- template styles -->
    <link rel="stylesheet" href="{% static 'css/qrowd.css' %}">
    <link rel="stylesheet" href="{% static 'css/qrowd-responsive.css' %}">
</head>

<body class="custom-cursor">

    <div class="custom-cursor__cursor"></div>
    <div class="custom-cursor__cursor-two"></div>





    {% comment %} <div class="preloader">
        <div class="preloader__image"></div>
    </div> {% endcomment %}
    <!-- /.preloader -->


    <div class="page-wrapper">
        {% include 'includes/navbar.html' %}

        {% block content %}
        
        {% endblock  %}

        <!--Site Footer Start-->
        {% include 'includes/footer.html' %}
        <!--Site Footer End-->


    </div><!-- /.page-wrapper -->

    {% include 'includes/mobile-nav.html' %}
    
    <!-- /.mobile-nav__wrapper -->

    <div class="search-popup">
        <div class="search-popup__overlay search-toggler"></div>
        <!-- /.search-popup__overlay -->
        <div class="search-popup__content">
            <form action="#">
                <label for="search" class="sr-only">search here</label><!-- /.sr-only -->
                <input type="text" id="search" placeholder="Search Here...">
                <button type="submit" aria-label="search submit" class="thm-btn">
                    <i class="icon-magnifying-glass"></i>
                </button>
            </form>
        </div>
        <!-- /.search-popup__content -->
    </div>
    <!-- /.search-popup -->

    <a href="#" data-target="html" class="scroll-to-target scroll-to-top"><i class="icon-right-arrow"></i></a>


    <script src="{% static 'vendors/jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendors/jarallax/jarallax.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-appear/jquery.appear.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-circle-progress/jquery.circle-progress.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-validate/jquery.validate.min.js' %}"></script>
    <script src="{% static 'vendors/nouislider/nouislider.min.js' %}"></script>
    <script src="{% static 'vendors/odometer/odometer.min.js' %}"></script>
    <script src="{% static 'vendors/swiper/swiper.min.js' %}"></script>
    <script src="{% static 'vendors/tiny-slider/tiny-slider.min.js' %}"></script>
    <script src="{% static 'vendors/wnumb/wNumb.min.js' %}"></script>
    <script src="{% static 'vendors/wow/wow.js' %}"></script>
    <script src="{% static 'vendors/isotope/isotope.js' %}"></script>
    <script src="{% static 'vendors/countdown/countdown.min.js' %}"></script>
    <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'vendors/bxslider/jquery.bxslider.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'vendors/vegas/vegas.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'vendors/timepicker/timePicker.js' %}"></script>
    <script src="{% static 'vendors/circleType/jquery.circleType.js' %}"></script>
    <script src="{% static 'vendors/circleType/jquery.lettering.min.js' %}"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>




    <!-- template js -->
    <script src="{% static 'js/qrowd.js' %}"></script>

    <script>
        $(document).ready(function() {
            $("#id_payment_deadline").datepicker({changeYear: true, changeMonth: true});
        })
    </script>
</body>

</html>